### ISSUE TITLE
Passing UID and GUID

### ISSUE THREAD

**Issue by undaunt** [Mumie-hub/docker-services#19]
Hello,

Just wondering if it's currently possible to enforce or change the UID and GUID now without them being environmental variables? I'm trying to utilize this container as a mount point to gsuite for a Nextcloud test and I cannot access an rclone lsd remote: or get it to interact with other containers since it seems to be running as root.

Thank you! Please let me know if there's a simple edit I could do on a copy of the downloaded container if that's easier.

**Comment by Mumie-hub** [comment]
hi :)! rclone is running as root, because its establishing a mountpoint with fuse.
The mountpoint itself (user, premissions) can be modified with the rclone MountCommands [mount.docs](https://rclone.org/commands/rclone_mount/).
For Nextcloud, your folder and files need to have uid 33 gid 33 and Mask 0770 (umask 007).
Example MountCommand in rclone would be:
-e MountCommands="--allow-other --uid 33 --gid 33 --umask 007 --default-permissions --allow-non-empty" and -v /host/mount/point:/mnt/mediaefs:shared (:shared is necessary and --cap-add SYS_ADMIN --device /dev/fuse --security-opt apparmor:unconfined)

Best Regards

**Comment by undaunt** [comment]
Hey, thanks very much! I'm running a compose and already have variables set to match my main user ID and the docker group set to ${PUID} and ${GUID}, so I'm thinking it should be something close to this:

`  rclone-cloud:
    image: mumiehub/rclone-mount
    container_name: rclone-cloud
    restart: always
    privileged: true
    devices:
      - /dev/fuse
    security_opt:
      - apparmor:unconfined
    cap_add:
      - SYS_ADMIN
    volumes:
      - ${USERDIR}/cloud:/mnt/mediafs:shared
      - ${USERDIR}/docker/rclone-cloud:/config
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - MountPoint="/mnt/mediafs"
      - MountCommands"--allow-other --uid ${PUID} --gid ${GUID) --umask 007 --default-permissions --allow-non-empty"
      - RemotePath="cloud-crypt:"`

But I'm getting an interpolation format error. Is there a proper way to put variables in the environment command?

**Comment by Mumie-hub** [comment]
Hi, some notes to the compose section.     
environment:
      - PUID=${PUID}
      - PGID=${PGID}
these to env args do nothing (there is no code in the script which will start rclone with this user).
Additionally rclone itself has to run as root, because only root can mount filesystems.
there is also missing 
`environment: /n 
- ConfigName="rclone.conf"`

**Comment by Mumie-hub** [comment]
can this be closed?

Best Regards

**Comment by undaunt** [comment]
Hey @Mumie-hub Sorry for the delay, was on the road for work. Can I read the above in detail and get back to you this weekend? Thank you.
