### ISSUE TITLE
EncFS remote filesystems

### ISSUE THREAD

**Issue by seffyroff** [Mumie-hub/docker-services#3]
I've forked this with the intention of adding EncFS - my existing rclone mount implementation has significant existing footprint that is encrypted with EncFS.  I don't know enough to understand best practice here - should I be running an EncFS mount inside the container or should I do that at the host level with the mounted volume from this container?  Advice here would be appreciated.  (I'm referring specifically to your rclone-mount Docker container here)

**Comment by Mumie-hub** [comment]
hi, first of all iam sure no expert :)! The rclone-mount Container mounts the cloud storage on the host, sharing the mount namespace of the host ( u can see it on the host with "findmnt | grep fuse" because otherwise the mount would only be available inside the Container and you had to setup a NFS Server inside the Container for example). If you are using EncFS on top of it, you sure could add it inside the Container or make a seperate one pointing at the host mount point of the rclone-mount Container with /host/mount:/mnt/container:slave
My approach is to not install anything on the host except docker engine, so i would just add another container with EncFS. But You can do as you like it best and use it on the host level :)!

**Comment by seffyroff** [comment]
I agree - the host should be as vanilla as possible to enable repeatable deployment, otherwise what's the point of running Docker? :)

I'll try either adding encfs to your container or running an additional encfs container next.  Thanks for your perspective!
